spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HariharanBaskarraj/InsuranceConfig.git
           
  application:
    name: INSURANCE-CONFIG-SERVER
    
server:
  port: 8888